"""Seed canonical_schema_registry via psycopg2."""
import subprocess, sys

SQL = """
INSERT INTO canonical_schema_registry
    (entity, column_name, display_name, es_column, jsonb_path, data_type,
     persona_scope, source_doc_type, encompass_field_id, is_required, notes)
VALUES
('loan','loan_amount','Loan Amount','loan_amount',NULL,'numeric','ltv_assessment,product_eligibility,rate_pricing','URLA_1003','2',TRUE,'Base loan amount; used for LTV calculation'),
('loan','purchase_price','Purchase Price','purchase_price',NULL,'numeric','ltv_assessment','PURCHASE_CONTRACT,URLA_1003','136',TRUE,'Contract price; LTV uses lesser of purchase price or appraised value'),
('loan','appraised_value','Appraised Value','appraised_value',NULL,'numeric','ltv_assessment','APPRAISAL_URAR','356',TRUE,'As-is appraised value from full 1004 URAR'),
('loan','ltv','Loan-to-Value Ratio','ltv',NULL,'float','ltv_assessment,rate_pricing,product_eligibility','DERIVED','',TRUE,'Computed: loan_amount / min(purchase_price, appraised_value)'),
('loan','interest_rate','Interest Rate','interest_rate',NULL,'float','rate_pricing,dti_calculation','URLA_1003','3',FALSE,'Note rate; ARM uses fully indexed rate for qualification'),
('loan','loan_type','Loan Type',NULL,'loan_terms.urla.loan_type','text','product_eligibility,compliance_check','URLA_1003','1172',TRUE,'Conventional/FHA/VA/USDA/Jumbo/NonQM'),
('loan','loan_purpose','Loan Purpose',NULL,'loan_terms.urla.loan_purpose','text','ltv_assessment,compliance_check','URLA_1003','19',TRUE,'purchase/refinance_rate_term/refinance_cash_out/construction'),
('loan','amortization_type','Amortization Type','amortization_type',NULL,'text','product_eligibility','URLA_1003','1041',FALSE,'fixed/arm/balloon/interest_only'),
('loan','lien_position','Lien Position','lien_position',NULL,'text','ltv_assessment,compliance_check','URLA_1003','420',FALSE,'first/second/third'),
('loan','loan_term_months','Loan Term Months',NULL,'loan_terms.urla.loan_term_months','integer','rate_pricing,dti_calculation','URLA_1003','4',FALSE,'360=30yr 180=15yr 120=10yr'),
('loan','hcltv','High Combined LTV',NULL,'loan_terms.hcltv','float','ltv_assessment,product_eligibility','DERIVED','',FALSE,'Includes subordinate financing'),
('applicant','first_name','First Name',NULL,'borrower.first_name','text','identity_verification','URLA_1003,DRIVERS_LICENSE','4000',TRUE,'Primary borrower first name'),
('applicant','last_name','Last Name',NULL,'borrower.last_name','text','identity_verification','URLA_1003,DRIVERS_LICENSE','4002',TRUE,'Primary borrower last name'),
('applicant','date_of_birth','Date of Birth',NULL,'borrower.date_of_birth','date','identity_verification','URLA_1003,DRIVERS_LICENSE','1402',FALSE,'Used for OFAC/SSA verification'),
('applicant','ssn_last4','SSN Last 4',NULL,'borrower.ssn_last4','text','identity_verification','URLA_1003','65',FALSE,'Last 4 of SSN for identity matching'),
('applicant','email','Email Address',NULL,'borrower.email','text','identity_verification','URLA_1003','1240',FALSE,'Primary borrower email'),
('applicant','phone','Phone Number',NULL,'borrower.phone','text','identity_verification','URLA_1003','66',FALSE,'Primary contact phone'),
('applicant','employment_status','Employment Status',NULL,'borrower.employment.employment_status','text','income_verification','VOE,PAYSTUB','FE0106',FALSE,'employed/self_employed/retired/unemployed/military'),
('applicant','employer_name','Employer Name',NULL,'borrower.employment.employer_name','text','income_verification','W2,VOE,PAYSTUB','FE0109',FALSE,'Current employer name'),
('applicant','years_employed','Years at Employer',NULL,'borrower.employment.years_employed','float','income_verification','VOE,URLA_1003','FE0110',FALSE,'<2yr triggers employment history review'),
('applicant','marital_status','Marital Status',NULL,'borrower.marital_status','text','compliance_check','URLA_1003','52',FALSE,'Married/Separated/Unmarried'),
('credit','mid_score','Middle Credit Score','mid_credit_score',NULL,'integer','credit_assessment,rate_pricing,product_eligibility','CREDIT_REPORT','1',TRUE,'Middle of 3 bureau scores'),
('credit','equifax_score','Equifax Score',NULL,'borrower.credit.equifax_score','integer','credit_assessment','CREDIT_REPORT','',FALSE,'Equifax FICO score'),
('credit','experian_score','Experian Score',NULL,'borrower.credit.experian_score','integer','credit_assessment','CREDIT_REPORT','',FALSE,'Experian FICO score'),
('credit','transunion_score','TransUnion Score',NULL,'borrower.credit.transunion_score','integer','credit_assessment','CREDIT_REPORT','',FALSE,'TransUnion FICO score'),
('credit','derogatory_count','Derogatory Count',NULL,'borrower.credit.derogatory_marks','integer','credit_assessment','CREDIT_REPORT','',FALSE,'Late payments collections judgments liens'),
('credit','open_tradelines','Open Tradelines',NULL,'borrower.credit.open_tradelines','integer','credit_assessment','CREDIT_REPORT','',FALSE,'<3 tradelines = thin file'),
('credit','credit_utilization','Credit Utilization',NULL,'borrower.credit.credit_utilization','float','credit_assessment','CREDIT_REPORT','',FALSE,'>30% is risk flag'),
('credit','active_bankruptcy','Active Bankruptcy',NULL,'borrower.credit.active_bankruptcy','boolean','credit_assessment','CREDIT_REPORT,COURT_DOCS','',FALSE,'True = automatic block'),
('credit','thin_file','Thin File Flag',NULL,'borrower.credit.thin_file','boolean','credit_assessment','CREDIT_REPORT','',FALSE,'<3 tradelines or <2yr history'),
('credit','credit_report_date','Credit Report Date','credit_report_date',NULL,'date','credit_assessment,closing_readiness','CREDIT_REPORT','1569',FALSE,'Must be within 120 days of closing'),
('credit','public_records_count','Public Records Count','public_records_count',NULL,'integer','credit_assessment','CREDIT_REPORT','',FALSE,'Bankruptcies judgments tax liens'),
('credit','inquiries_last_90','Inquiries Last 90 Days','inquiries_last_90',NULL,'integer','credit_assessment,fraud_screening','CREDIT_REPORT','',FALSE,'>6 is fraud signal'),
('income','qualifying_monthly','Qualifying Monthly Income','qualifying_monthly',NULL,'float','income_verification,dti_calculation','W2,PAYSTUB,TAX_RETURN','1',TRUE,'Gross monthly qualifying income after adjustments'),
('income','co_borrower_qualifying_monthly','Co-Borrower Monthly Income','co_borrower_qualifying_monthly',NULL,'float','income_verification,dti_calculation','W2,PAYSTUB','',FALSE,'Co-borrower qualifying monthly income'),
('income','combined_monthly_income','Combined Monthly Income','combined_monthly_income',NULL,'float','income_verification,dti_calculation','DERIVED','',FALSE,'Primary + co-borrower combined'),
('income','income_type','Income Type',NULL,'borrower.income.income_type','text','income_verification','W2,1099,TAX_RETURN,SSA_AWARD_LETTER','',FALSE,'W2/SELF_EMPLOYED/1099/SSA/PENSION/RENTAL/ALIMONY/MILITARY'),
('income','base_salary','Base Annual Salary',NULL,'borrower.income.base_salary','float','income_verification','W2,PAYSTUB,OFFER_LETTER','FE0104',FALSE,'Base salary only; bonuses separate'),
('income','bonus_income','Bonus/Commission Income',NULL,'borrower.income.bonus_income','float','income_verification','PAYSTUB,W2,TAX_RETURN','',FALSE,'Recurring only; requires 2yr history'),
('income','rsu_income','RSU/Stock Income',NULL,'borrower.income.rsu_income','float','income_verification','W2,BROKERAGE_STMT','',FALSE,'Requires 3yr history + employer confirmation'),
('income','rental_income_gross','Gross Rental Income',NULL,'borrower.income.rental_income_gross','float','income_verification','SCHEDULE_E,LEASE_AGREEMENT','',FALSE,'75% used for qualifying; 2yr Schedule E required'),
('income','alimony_income','Alimony Income',NULL,'borrower.income.alimony_income','float','income_verification','DIVORCE_DECREE,COURT_ORDER','',FALSE,'Requires 3yr+ continuance'),
('income','social_security_income','SSA Income',NULL,'borrower.income.social_security_income','float','income_verification','SSA_AWARD_LETTER','',FALSE,'Non-taxable; gross up 25%'),
('income','pension_income','Pension Income',NULL,'borrower.income.pension_income','float','income_verification','PENSION_STATEMENT','',FALSE,'Fixed retirement income; non-taxable grossed up 25%'),
('income','ytd_gross','YTD Gross Pay',NULL,'borrower.income.ytd_gross','float','income_verification','PAYSTUB','',FALSE,'YTD gross annualized for income calculation'),
('income','income_confidence','Income Confidence Score',NULL,'borrower.income.confidence','float','income_verification','DERIVED','',FALSE,'<0.80 triggers escalation per Capital Loans policy'),
('qualification','back_end_dti','Back-End DTI','dti_back',NULL,'float','dti_calculation,rate_pricing,product_eligibility','DERIVED','1',TRUE,'Total obligations / qualifying income; max 45%'),
('qualification','front_end_dti','Front-End DTI','dti_front',NULL,'float','dti_calculation','DERIVED','',FALSE,'PITI only / qualifying income'),
('qualification','piti_monthly','Monthly PITI','piti_monthly',NULL,'float','dti_calculation,asset_verification,closing_readiness','DERIVED','',TRUE,'Principal + Interest + Taxes + Insurance'),
('qualification','monthly_obligations','Monthly Debt Obligations','monthly_obligations',NULL,'float','dti_calculation,asset_verification','CREDIT_REPORT','',TRUE,'All recurring monthly debts; IBR/deferred use 1% rule'),
('qualification','total_monthly_debt','Total Monthly Debt',NULL,'borrower.qualification.total_monthly_debt','float','dti_calculation','CREDIT_REPORT','',FALSE,'Non-housing monthly obligations'),
('qualification','residual_income','Residual Income VA','residual_income',NULL,'float','dti_calculation','DERIVED','1292',FALSE,'VA requirement: income - obligations - property expense'),
('qualification','reserves_months','Reserves Months PITI',NULL,'borrower.assets.reserves_months','float','asset_verification','DERIVED','',TRUE,'Liquid assets / PITI; min 3mo standard 6mo Jumbo'),
('asset','total_liquid_assets','Total Liquid Assets','total_liquid_assets',NULL,'float','asset_verification,closing_readiness','BANK_STATEMENT','',TRUE,'Verified checking + savings'),
('asset','checking_balance','Checking Balance',NULL,'borrower.assets.checking_balance','float','asset_verification','BANK_STATEMENT','',FALSE,'Most recent 2-month average'),
('asset','savings_balance','Savings Balance',NULL,'borrower.assets.savings_balance','float','asset_verification','BANK_STATEMENT','',FALSE,'Verified savings balance'),
('asset','retirement_balance','Retirement Balance',NULL,'borrower.assets.retirement_balance','float','asset_verification','RETIREMENT_STATEMENT','',FALSE,'60% usable for reserves'),
('asset','brokerage_balance','Brokerage Balance',NULL,'borrower.assets.brokerage_balance','float','asset_verification','BROKERAGE_STATEMENT','',FALSE,'70% usable after 30% haircut'),
('asset','gift_amount','Gift Funds Amount',NULL,'borrower.assets.gift_amount','float','asset_verification','GIFT_LETTER,BANK_STATEMENT','',FALSE,'Gift letter + transfer proof required'),
('asset','large_deposit_amount','Large Deposit Amount',NULL,'borrower.assets.large_deposit_amount','float','asset_verification','BANK_STATEMENT','',FALSE,'>50% monthly income must be sourced'),
('property','property_state','Property State',NULL,'property.property_state','text','compliance_check,product_eligibility','URLA_1003','12',TRUE,'Two-letter state code'),
('property','property_zip','Property ZIP',NULL,'property.property_zip','text','compliance_check,product_eligibility','URLA_1003','15',FALSE,'ZIP for USDA eligibility and flood zone'),
('property','property_county','Property County',NULL,'property.property_county','text','compliance_check','URLA_1003','13',FALSE,'County for CRA assessment area'),
('property','property_type','Property Type',NULL,'property.property_type','text','product_eligibility,ltv_assessment','URLA_1003','16',TRUE,'SFR/Condo/Townhouse/2-4Unit/Manufactured'),
('property','occupancy_type','Occupancy Type',NULL,'property.occupancy_type','text','ltv_assessment,product_eligibility','URLA_1003','1811',TRUE,'primary_residence/second_home/investment'),
('property','property_address','Property Address',NULL,'property.property_address','text','compliance_check','URLA_1003','11',FALSE,'Subject property street address'),
('property','property_city','Property City',NULL,'property.property_city','text','compliance_check','URLA_1003','12',FALSE,'Subject property city'),
('property','flood_zone','FEMA Flood Zone',NULL,'property.flood_zone','text','closing_readiness','FLOOD_CERTIFICATE','',FALSE,'Zone AE/A requires mandatory flood insurance'),
('property','hoa_monthly','HOA Monthly Dues',NULL,'property.hoa_monthly','float','dti_calculation','HOA_STATEMENT,CONDO_QUESTIONNAIRE','',FALSE,'HOA dues included in PITI for DTI'),
('aus','recommendation','AUS Recommendation',NULL,'loan_terms.aus_findings.recommendation','text','aus_result','DU_FINDINGS,LP_FINDINGS,GUS_FINDINGS','',TRUE,'APPROVE/ELIGIBLE/REFER/REFER_WITH_CAUTION/INELIGIBLE'),
('aus','aus_system','AUS System',NULL,'loan_terms.aus_findings.system','text','aus_result','DU_FINDINGS,LP_FINDINGS,GUS_FINDINGS','',FALSE,'DU/LP/GUS'),
('aus','aus_case_number','AUS Case Number',NULL,'loan_terms.aus_findings.case_number','text','aus_result','DU_FINDINGS,LP_FINDINGS','',FALSE,'Unique AUS submission reference'),
('aus','aus_submission_count','AUS Submission Count','aus_submission_count',NULL,'integer','aus_result','DERIVED','',FALSE,'Number of AUS submissions'),
('aus','manual_review_required','Manual Review Required','manual_review_required',NULL,'boolean','aus_result','DERIVED','',FALSE,'True when AUS refers or DTI in senior UW zone'),
('fraud','fraud_score','Fraud Risk Score',NULL,'borrower.identity.fraud_score','float','fraud_screening','VENDOR_LEXISNEXIS,VENDOR_CORELOGIC','',TRUE,'>0.70 triggers block per Capital Loans policy'),
('fraud','identity_match_confidence','Identity Match Confidence',NULL,'borrower.identity.identity_match_confidence','float','fraud_screening','VENDOR_LEXISNEXIS','',FALSE,'Low score triggers manual review'),
('fraud','watchlist_match','OFAC Watchlist Match',NULL,'borrower.identity.watchlist_match','boolean','compliance_check,fraud_screening','VENDOR_OFAC_CHECK','',FALSE,'Requires compliance clearance'),
('fraud','synthetic_identity_flag','Synthetic Identity Flag',NULL,'borrower.identity.synthetic_identity_flag','boolean','fraud_screening','VENDOR_LEXISNEXIS','',FALSE,'AI-detected synthetic identity'),
('compliance','action_taken','HMDA Action Taken','action_taken',NULL,'text','compliance_check','DERIVED','',FALSE,'originated/approved_not_accepted/denied/withdrawn'),
('compliance','lien_status_hmda','HMDA Lien Status','lien_status_hmda',NULL,'text','compliance_check','DERIVED','',FALSE,'secured_by_first_lien/secured_by_subordinate_lien'),
('compliance','hmda_complete','HMDA Complete Flag',NULL,'verifications.hmda_complete','boolean','compliance_check','DERIVED','',FALSE,'All HMDA LAR fields populated'),
('compliance','fair_lending_flag','Fair Lending Flag',NULL,'verifications.fair_lending_violation','boolean','compliance_check','DERIVED','',FALSE,'Potential fair lending issue detected'),
('compliance','state_rules_passed','State Rules Passed',NULL,'verifications.state_rules_passed','boolean','compliance_check','DERIVED','',FALSE,'All state lending regulations satisfied'),
('employment','employer_name','Employer Name',NULL,'borrower.employment.employer_name','text','income_verification','W2,VOE,PAYSTUB','FE0109',FALSE,'Must match W2 VOE and pay stub'),
('employment','employment_type','Employment Type',NULL,'borrower.employment.employment_type','text','income_verification','VOE,URLA_1003','',FALSE,'full_time/part_time/self_employed/seasonal/contract/military'),
('employment','start_date','Employment Start Date',NULL,'borrower.employment.start_date','date','income_verification','VOE,PAYSTUB','FE0107',FALSE,'<2yr triggers employment history review'),
('employment','pay_frequency','Pay Frequency',NULL,'borrower.employment.pay_frequency','text','income_verification','PAYSTUB','',FALSE,'weekly/biweekly/semi_monthly/monthly'),
('coborrower','co_first_name','Co-Borrower First Name',NULL,'co_borrowers.0.first_name','text','identity_verification','URLA_1003','4004',FALSE,'Primary co-borrower first name'),
('coborrower','co_last_name','Co-Borrower Last Name',NULL,'co_borrowers.0.last_name','text','identity_verification','URLA_1003','4006',FALSE,'Primary co-borrower last name'),
('coborrower','co_mid_score','Co-Borrower Credit Score',NULL,'co_borrowers.0.credit.mid_score','integer','credit_assessment','CREDIT_REPORT','',FALSE,'Governing score = lower of primary vs co-borrower'),
('coborrower','co_employment_status','Co-Borrower Employment Status',NULL,'co_borrowers.0.employment.employment_status','text','income_verification','VOE,W2,PAYSTUB','',FALSE,'Co-borrower employment status'),
('coborrower','co_qualifying_monthly','Co-Borrower Qualifying Income','co_borrower_qualifying_monthly',NULL,'float','income_verification,dti_calculation','W2,PAYSTUB,TAX_RETURN','',FALSE,'Co-borrower gross monthly qualifying income'),
('coborrower','non_occupant_coborrower','Non-Occupant Co-Borrower',NULL,'co_borrowers.0.non_occupant','boolean','product_eligibility','URLA_1003','',FALSE,'FHA allows; Conventional limits')
ON CONFLICT (entity, column_name) DO UPDATE SET
    display_name=EXCLUDED.display_name, es_column=EXCLUDED.es_column,
    jsonb_path=EXCLUDED.jsonb_path, data_type=EXCLUDED.data_type,
    persona_scope=EXCLUDED.persona_scope, source_doc_type=EXCLUDED.source_doc_type,
    encompass_field_id=EXCLUDED.encompass_field_id, is_required=EXCLUDED.is_required,
    notes=EXCLUDED.notes;
"""

import subprocess
result = subprocess.run([
    "docker", "run", "--rm", "postgres:15", "psql",
    "postgresql://edms_admin:edms_dev@edms-postgres-rdsinstance-ev3113lmj40h.caxie60g4jth.us-east-1.rds.amazonaws.com:5432/edms",
    "-c", SQL
], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)
