"""
Condition Collector — CN-B

Collects all conditions generated by resolver personas during a decision run
and writes them to loan_condition_instances (via ConditionEngine).

NB on storage shape: decision_outputs has NO `persona_outputs` column. The
runner writes one row per decision_id, and each persona's output_payload is
stored in that row's `context_snapshot` (jsonb). So the collector iterates the
latest version of every decision row for the application, and the persona name
== the `decision_id` column.

Sources of conditions (per-persona payload key inside context_snapshot):
  title_assessment    -> conditions_generated
  credit_assessment   -> conditions
  asset_verification  -> asset_conditions
  fraud_screening     -> fraud_conditions
  product_eligibility -> collateral_conditions

Each condition dict {code, text, blocks, prior_to} is written via
ConditionEngine.create_condition() — idempotent (UNIQUE app/tenant/code),
safe to re-run.
"""

import json
from typing import Optional

from .condition_engine import ConditionEngine


# Map decision/persona name -> context_snapshot key holding the condition list.
PERSONA_CONDITION_KEYS = {
    'title_assessment':          'conditions_generated',
    'credit_assessment':         'conditions',
    'asset_verification':        'asset_conditions',
    'fraud_screening':           'fraud_conditions',
    'product_eligibility':       'collateral_conditions',
    'closing_readiness':         'conditions',
    'income_verification':       'income_conditions',
    'employment_reconciliation': 'conditions',
    'compliance_check':          'conditions',
}

# Fallback keys to scan when the mapped key is absent/empty.
_FALLBACK_KEYS = [
    'conditions',
    'conditions_generated',
    'asset_conditions',
    'fraud_conditions',
    'collateral_conditions',
]


class ConditionCollector:

    def __init__(self, conn):
        self.conn = conn
        self.engine = ConditionEngine(conn)

    @staticmethod
    def _extract_conditions(decision_id: str, payload: dict) -> list:
        """Pull the condition list out of a persona's output_payload."""
        cond_key = PERSONA_CONDITION_KEYS.get(decision_id)
        if cond_key and isinstance(payload.get(cond_key), list):
            if payload[cond_key]:
                return payload[cond_key]
        for key in _FALLBACK_KEYS:
            val = payload.get(key)
            if isinstance(val, list) and val:
                return val
        return []

    async def collect_from_decision(
        self,
        application_id: str,
        tenant_id: str,
        decision_id: Optional[str] = None,
    ) -> dict:
        """
        Read the latest decision_outputs rows for the application, extract
        conditions from each persona's context_snapshot, and write them to
        loan_condition_instances.
        """
        # Latest version of every decision row for this loan.
        rows = await self.conn.fetch('''
            SELECT DISTINCT ON (decision_id)
                   id, decision_id, context_snapshot
            FROM decision_outputs
            WHERE application_id = $1
            AND tenant_id = $2
            ORDER BY decision_id, version DESC
        ''', application_id, tenant_id)

        if not rows:
            return {
                'error': 'No decisions found',
                'total_created': 0,
                'total_skipped': 0,
                'by_persona': {},
                'application_id': application_id,
            }

        total_created = 0
        total_skipped = 0
        by_persona = {}

        for row in rows:
            dec_name = row['decision_id']
            row_id = str(row['id'])
            payload = row['context_snapshot']
            if isinstance(payload, str):
                try:
                    payload = json.loads(payload)
                except (ValueError, TypeError):
                    continue
            if not isinstance(payload, dict):
                continue

            conditions = self._extract_conditions(dec_name, payload)
            # Only keep dicts that carry a code.
            conditions = [
                c for c in conditions
                if isinstance(c, dict) and c.get('code')
            ]
            if not conditions:
                continue

            result = await self.engine.create_from_resolver_output(
                application_id=application_id,
                tenant_id=tenant_id,
                conditions=conditions,
                generated_by=dec_name,
                decision_id=row_id,
            )
            if result['created'] > 0:
                by_persona[dec_name] = result['created']
                total_created += result['created']
            total_skipped += result['skipped']

        return {
            'total_created': total_created,
            'total_skipped': total_skipped,
            'by_persona': by_persona,
            'application_id': application_id,
        }

    async def collect_all_meridian(self) -> dict:
        """Collect conditions for all 16 scenarios."""
        rows = await self.conn.fetch('''
            SELECT DISTINCT application_id
            FROM entity_states
            WHERE tenant_id = 'meridian'
            ORDER BY application_id
        ''')

        results = {}
        for r in rows:
            app_id = r['application_id']
            result = await self.collect_from_decision(
                app_id, 'meridian'
            )
            if result.get('total_created', 0) > 0:
                results[app_id] = result

        return results


__all__ = ["ConditionCollector", "PERSONA_CONDITION_KEYS"]
